### ISSUE TITLE
Slashes in Encryption result

### ISSUE THREAD

**Issue by idodidodi** [Snack-X/rijndael-js#2]
Hi, 
I have a problem with the slashes in encryption result. 
While there are slashes I can't use the encryption string as a token in the url link, because it confuses the router. 
My Vue.js router expects something like that: 
path: '/:token',  // http://localhost:8080/#/
But when it get this: 
http://localhost:8080/#/ySWUWGwOqEtJIavEAQk9c4RiF6X7cF3y2tshAYDFz/4=
it cannot read the token.
An example of the encryption result: ySWUWGwOqEtJIavEAQk9c4RiF6X7cF3y2tshAYDFz/4=

I am sure I can change definitions in routes, but wouldn't it be easier if there would be no slashes in the encrtiotion result, like there are no '&' chars.

What do you think?

**Comment by Snack-X** [comment]
I think it's not directly caused by this module.

You might need to use [`base64url` encoding](https://tools.ietf.org/html/rfc4648#section-5). Basically, `-` and `_` instead of `+` and `/`, which are not URL-safe characters.

You can achieve this with something like `BASE64_STRING.replace(/\-/g, '+').replace(/_/g, '/')`.

**Comment by idodidodi** [comment]
Okay, thanks a lot.
When I changed it to query string the browser replace those char with URL
chars.

But I'll consider your suggestion and check support for all the browsers
before I deploy my app.



עידו

**Comment by idodidodi** [comment]
Okay, 
I have a some more questions.

1. Are '/' and '+' the only non safe URL characters in this module?
2. Do '_' and '-' never appear in this module? 
  If they don't so I can safely replace all their instances with '/' and '+' after getting the token from the URL. 

Thanks a lot.

> I think it's not directly caused by this module.
> 
> You might need to use [`base64url` encoding](https://tools.ietf.org/html/rfc4648#section-5). Basically, `-` and `_` instead of `+` and `/`, which are not URL-safe characters.
> 
> You can achieve this with something like `BASE64_STRING.replace(/\-/g, '+').replace(/_/g, '/')`.

**Comment by Snack-X** [comment]
If you are using it in Node.js environment with `.toString(‘base64’)`, you are 100% fine. Base64 is a standard data encoding format.

**Comment by idodidodi** [comment]
Actually I do use Node.js environment, and toString('base64')
 const encryptedStr = encrypted.toString('base64');
    console.log('Encrypt output: ', encryptedStr);
but the output comes as this:
7JHcGZ59xGe/vPFYMtpeJer6pfpJ4fROXZcA1XJSsm4=
With non safe URL chars.

עידו
