### ISSUE TITLE
how to use PaddingMode

### ISSUE THREAD

**Issue by bag7dad** [Snack-X/rijndael-js#5]
```
                       crypto = new RijndaelManaged();
			crypto.Key = key;
			crypto.IV = new byte[16];
			crypto.Padding = PaddingMode.PKCS7;
```

about key and IV its ok what about Padding ?
or its not important?

**Comment by Snack-X** [comment]
Padding is not part of this library.

PKCS is a well-defined standard, and PKCS padding method can be applied separately outside this library.

* https://tools.ietf.org/html/rfc5652#section-6.3
